<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{ebf68f6f-cb24-4b94-876b-484c15003446}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	i : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[i := i + 1;

IpcDiagnostics();		// first way to implement the IPC diagnostics

//IpcDiagnostics_2();		// second way to implement the IPC diagnostics
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>